name: pim
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.5.2
  - pip
  - pip:
      - scikit-learn==1.1.1
      - mlflow>=1.0
      - pandas
      - requests
      - click
      - rich
      - z3-solver
