name: master-thesis-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.5.2
  - pip
  - pip:
      - scikit-learn==1.1.1
      - mlflow>=1.0
      - pandas
      - requests
      - click
      - rich
      - git+https://github.com/smba/pycosa-toolbox.git@main
      - xmlschema
      - git+https://github.com/mailach/SPLC2py.git@main 

