systems:
  Apache:
    domain: Web Server
    year: 2012
    authors: Guo et al.
    paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6693089
    configurations: 192
    features: 9
    all_measured: True
    binary_features: True
    numeric_features: False
    nfp: [ResponseRate]
  BerkeleyDBC: 
    domain: Database
    year: 2012
    authors: Guo et al.
    paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6693089
    configurations: 2560
    features: 18
    all_measured: True
    binary_features: 18
    numeric_features: 0
    nfp: [Performance]
  BerkeleyDBJ:
    domain: Database
    year: 2012
    authors: Guo et al.
    paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6693089
    configurations: 400
    features: 26
    all_measured: True
    binary_features: 26
    numeric_features: 0
    nfp: [Performance]
  Dune:
    domain: Multi-Grid Solver
    year: 2015
    authors: Siegmund et al.
    paper: https://dl.acm.org/doi/pdf/10.1145/2786805.2786845
    configurations: 2304
    features: 11
    constraints: 20
    all_measured: True
    binary_features: 8
    numeric_features: 3
    nfp: [Performance]
  HIPAcc:
    domain: Image Processing
    year: 2015
    authors: Siegmund et al.
    paper: https://dl.acm.org/doi/pdf/10.1145/2786805.2786845
    configurations: 13485
    features: 33
    constraints: 416
    all_measured: True
    binary_features: 31
    numeric_features: 2
    nfp: [Performance]
  x264:
    domain: Encoder
    measurements: 
    year: 2012
    authors: Guo et al.
    paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6693089
    configurations: 1152
    features: 16
    all_measured: True
    binary_features: 16
    numeric_features: 0
    nfp: [Performance]